export const FETCH_COLLECTION_REQUEST = 'FETCH_COLLECTION_REQUEST';
export const FETCH_COLLECTION_FAILURE = 'FETCH_COLLECTION_FAILURE';
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS';

export const FETCH_PICTURE_INFO_REQUEST = 'FETCH_PICTURE_INFO_REQUEST';
export const FETCH_PICTURE_INFO_FAILURE = 'FETCH_PICTURE_INFO_FAILURE';
export const FETCH_PICTURE_INFO_SUCCESS = 'FETCH_PICTURE_INFO_SUCCESS';

export const HANDLE_PAGE_SIZE = 'HANDLE_PAGE_SIZE';
export const HANDLE_PAGE_NUMBER = 'HANDLE_PAGE_NUMBER';
export const HANDLE_SEARCH = 'HANDLE_SEARCH';
export const HANDLE_ORDER = 'HANDLE_ORDER';
export const RESET_QUERY_PARAM = 'RESET_QUERY_PARAM';

export const HANDLE_SELECT_PAGE_SIZE_VISABILITY = 'HANDLE_SELECT_PAGE_SIZE_VISABILITY';
export const HANDLE_SELECT_ORDER_BY_LIST_VISABILITY = 'HANDLE_SELECT_ORDER_BY_LIST_VISABILITY';

export const OPEN_PICTURE_DETAILS_POP_UP = 'OPEN_PICTURE_DETAILS_POP_UP';
export const CLOSE_PICTURE_DETAILS_POP_UP = 'CLOSE_PICTURE_DETAILS_POP_UP';
export const SHOW_PICTURE_TITLE = 'SHOW_PICTURE_TITLE';
export const HIDE_PICTURE_TITLE = 'HIDE_PICTURE_TITLE';

